### ISSUE TITLE
Error when clicking on Orders in Receiving app for anyone but Admin

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#150]
(this is reported on #folio-support Slack)

1. open Receiving app
2. find some Orders (filter by Order Status = open)
3. click on an Order

anyone who does **not** have Admin PSet gets this error:
`Something went wrong
An error occurred on this page and it could not be loaded. View error details
Return to Receiving landing page`

and "toast": `Failed to load Title or PO line data`

When you click `View error details` you get
```
URL: https://folio-test.stanford.edu/receiving/07b0423a-e6a3-48a9-94b4-a7059119c408/view?limit=50&offset=0&purchaseOrder.workflowStatus=Pending

Error: TypeError: Cannot read properties of undefined (reading 'undefined')

Stack: at Qr (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7288554)
at aa (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13115735)
at Vs (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13167784)
at Rc (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13155058)
at Sc (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13154986)
at Pc (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13154849)
at yc (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13151836)
at https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13101657
at t.unstable_runWithPriority (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13588019)
at Wo (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13101434)

at Qr (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7287625)
at r (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13338371)
at un (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7298047)
at i (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8643892)
at m (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8405020)
at y (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13311335)
at u (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8806673)
at s (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8436260)
at r (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13338371)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13335817)
at div
at A (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8210766)
at u (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8217653)
at y (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8229811)
at h (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9466869)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9100475)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9117788)
at HotKeys-t
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7945273)
at zn (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7310405)
at r (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13338371)
at vo (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7320694)
at i (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8643892)
at m (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8405020)
at y (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13311335)
at u (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8806673)
at s (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8436260)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13335817)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13337834)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9100475)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9117788)
at HotKeys-t
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7945273)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9100475)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9117788)
at HotKeys-t
at c (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7942674)
at Li (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:7366310)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8458478)
at h
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8461904)
at s (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8436260)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8508826)
at ic (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8649857)
at div
at u (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8446806)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8649380)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13335817)
at Cc (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8655649)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13337834)
at main
at pd (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8703181)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8665820)
at div
at ru (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8663990)
at s (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8662765)
at u (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8453580)
at r (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13338371)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13332443)
at l (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13309385)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9100475)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:9117788)
at HotKeys-t
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8458478)
at h
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8461904)
at s (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8436260)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8659442)
at injectIntl(a)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8778601)
at t (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13236958)
at c (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13290780)
at St (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8502168)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8508826)
at c (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8784232)
at u (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8453580)
at y (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:13311335)
at a (https://folio-test.stanford.edu/bundle.0e19e49f5c3ad616eabc.js:2:8791378)
```

**NOTE** I gave Testy Tester user **all** available permissions in the UI, and Testy Tester gets the same error. But Admin PSet **can** successfully click on Orders and view details. Does Admin PSet have some invisible permissions?

I tried this with several different orders, all gave the error.

![Screen Shot 2022-08-15 at 10.10.47 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/0881495e-5a69-427a-bda9-a66e0d3e0e90)

![Screen Shot 2022-08-15 at 10.11.00 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/772f1ce6-55c9-48fd-8138-fdb6920dc12d)

**Comment by shelleydoljack** [comment]
Using chrome, I logged into folio-test with the admin user and removed the Admin pset from my user account. I gave my user the psets: Access 4, Acquisitions Staff 5, Cataloging Staff 5, E-Resources 5 (same psets as the user who originally reported this in Slack). I then cleared my browser cookies and cached and logged in via SSO. I navigated to the Receiving app, faceted by open and pending and did not experience the error reported.
![Screen Shot 2022-08-15 at 1 49 26 PM](https://user-images.githubusercontent.com/6343464/184707378-e40a465e-dd18-4abc-97ba-d2d1460cecda.png)
![Screen Shot 2022-08-15 at 1 50 15 PM](https://user-images.githubusercontent.com/6343464/184707385-8267dbac-f149-465a-b3f0-f3011b95caad.png)

**Comment by michelleif** [comment]
weird because Testy Tester has **all visible** permissions and gets the error.

Does the Admin Pset have invisible perms? if so, would those still apply to your user even if you removed the Admin Pset in the UI? In our matrix, Admin Pset has these, which do not show up in the UI, so I don't even know how to give any of them to Testy Tester to see if those remove the error:
```
All orders-storage-module perms
inventory storage module - all authorities permissions
inventory storage module - all permissions
Source Record Storage - all permissions
```

could you try creating a fresh account and giving that account these PSets: Access 4, Acquisitions Staff 5, Cataloging Staff 5, E-Resources 5 and see if that works?

**Comment by shelleydoljack** [comment]
I think the problem is with the assigned (or not assigned) acquisitions unit. The original reporter should be assigned the LAW acq unit but I do not see that this user is in that acq unit. Add testy tester to SUL acq unit and it should work.

**Comment by shelleydoljack** [comment]
Also, you might find the Settings > Developer > Permissions inspector tool helpful with troubleshooting.
![Screen Shot 2022-08-15 at 2 06 16 PM](https://user-images.githubusercontent.com/6343464/184709488-d528d498-27e7-468a-9f37-ac27d0e87d0a.png)

**Comment by michelleif** [comment]
@shelleydoljack you are a genius! i put Testy in the SUL acq unit and it works!

Esther Chen's account was set up manually after the initial user import, so that might explain why the Acq Unit was missed. I will set to law and ask her to try again.

Suzette was getting same error, and she is NOT currently in SUL Acq unit altho she is listed as such in Matrix. maybe because her account was set up **before** the user load? I'll add her and ask her to try again.

**Is there a way to find staff users who are not assigned to an Acq unit to see if any others got missed?**

Thanks for info on Permissions Inspector, how did you get from above to figuring out that Acq unit permission was missing?

**Comment by shelleydoljack** [comment]
> how did you get from above to figuring out that Acq unit permission was missing?

It didn't seem like a permissions issue.

For the acq unit issue, maybe use gsheet to compare what's in the permissions matrix for an acq unit with the listing of users in an acq unit in FOLIO. There's not a way to get who does not have membership in an acq unit.

**Comment by michelleif** [comment]
Suzette can successfully click on Orders in receiving now; waiting to hear from Esther

**Comment by michelleif** [comment]
Esther can as well; closing.
